import { StateCreator } from "zustand";
import { ResultType } from "eecircuit-engine";
import { SimulationType } from "../types/commonTypes";

// Define the store interface that includes both simulation and tab slices
interface StoreWithTab {
  // Tab management
  isSimulateTabEnabled: boolean;
  mainTabValue: "schematic" | "simulate" | "plot";
  setIsSimulateTabEnabled: (enabled: boolean) => void;
  setMainTabValue: (tab: "schematic" | "simulate" | "plot") => void;
}

// Simulation state and actions
export interface SimulationState {
  // Netlist and simulation results
  netList: string;
  results: ResultType[];

  // Simulation configuration
  selectedSimType: SimulationType["type"];
  simulationConfig?: SimulationType;
  allSimulationConfigs: SimulationType[];
}

export interface SimulationActions {
  // Netlist and simulation actions
  setNetList: (netList: string) => void;
  setResults: (results: ResultType[]) => void;

  // Simulation configuration actions
  setSelectedSimType: (type: SimulationType["type"]) => void;
  setSimulationConfig: (config?: SimulationType) => void;
  setAllSimulationConfigs: (configs: SimulationType[]) => void;
  addSimulationConfig: (config: SimulationType) => void;
  updateSimulationConfig: (index: number, config: SimulationType) => void;
  deleteSimulationConfig: (index: number) => void;

  // Combined actions for common operations
  exportNetlist: (netlist: string) => void;
}

export type SimulationSlice = SimulationState & SimulationActions;

export const createSimulationSlice: StateCreator<
  SimulationSlice & StoreWithTab,
  [],
  [],
  SimulationSlice
> = (set) => ({
  // Initial state
  netList: "",
  results: [],
  selectedSimType: "None",
  simulationConfig: undefined,
  allSimulationConfigs: [],

  // Netlist and simulation actions
  setNetList: (netList) => set({ netList }),
  setResults: (results) => set({ results }),

  // Simulation configuration actions
  setSelectedSimType: (type) => set({ selectedSimType: type }),
  setSimulationConfig: (config) => set({ simulationConfig: config }),
  setAllSimulationConfigs: (configs) => set({ allSimulationConfigs: configs }),

  addSimulationConfig: (config) =>
    set((state: SimulationSlice) => ({
      allSimulationConfigs: [...state.allSimulationConfigs, config],
    })),

  updateSimulationConfig: (index, config) =>
    set((state: SimulationSlice) => ({
      allSimulationConfigs: state.allSimulationConfigs.map((c, i) =>
        i === index ? config : c
      ),
    })),

  deleteSimulationConfig: (index) =>
    set((state: SimulationSlice) => ({
      allSimulationConfigs: state.allSimulationConfigs.filter(
        (_, i) => i !== index
      ),
    })),

  // Combined actions for common operations
  exportNetlist: (netlist) => {
    const netListPreamble = `
* Netlist generated by EEcircuit
.include modelcard.CMOS90
`;
    const netlistWithPreamble = netListPreamble + netlist;

    set({
      netList: netlistWithPreamble,
      isSimulateTabEnabled: true,
      mainTabValue: "simulate",
    });
  },
});
