import { StateCreator } from "zustand";
import { ResultType } from "eecircuit-engine";
import { SimulationType } from "../types/commonTypes";
import type { BracketOperation } from "../utils/bracketParser";
import type { ParallelSimulationResult } from "../simulation/parallelSimulation";
import type { AggregatedResult } from "../simulation/resultAggregator";

// Define the store interface that includes both simulation and tab slices
interface StoreWithTab {
  // Tab management
  isSimulateTabEnabled: boolean;
  isPlotTabEnabled: boolean;
  mainTabValue: "schematic" | "simulate" | "plot";
  setIsSimulateTabEnabled: (enabled: boolean) => void;
  setIsPlotTabEnabled: (enabled: boolean) => void;
  setMainTabValue: (tab: "schematic" | "simulate" | "plot") => void;
}

// Simulation state and actions
export interface SimulationState {
  // Netlist and simulation results
  netList: string;
  results: ResultType[];

  // Simulation configuration
  selectedSimType: SimulationType["type"];
  simulationConfig?: SimulationType;
  allSimulationConfigs: SimulationType[];

  // Bracket operation state
  bracketOperation?: BracketOperation;
  isParallelSimulationRunning: boolean;
  parallelSimulationProgress: {
    total: number;
    completed: number;
    successful: number;
    failed: number;
  };
  parallelSimulationResults?: ParallelSimulationResult;
}

export interface SimulationActions {
  // Netlist and simulation actions
  setNetList: (netList: string) => void;
  setResults: (results: ResultType[]) => void;

  // Simulation configuration actions
  setSelectedSimType: (type: SimulationType["type"]) => void;
  setSimulationConfig: (config?: SimulationType) => void;
  setAllSimulationConfigs: (configs: SimulationType[]) => void;
  addSimulationConfig: (config: SimulationType) => void;
  updateSimulationConfig: (index: number, config: SimulationType) => void;
  deleteSimulationConfig: (index: number) => void;

  // Bracket operation actions
  setBracketOperation: (bracketOp?: BracketOperation) => void;
  setParallelSimulationRunning: (running: boolean) => void;
  updateParallelSimulationProgress: (progress: { total: number; completed: number; successful: number; failed: number }) => void;
  setParallelSimulationResults: (results?: ParallelSimulationResult) => void;
  resetParallelSimulation: () => void;

  // Combined actions for common operations
  exportNetlist: (netlist: string) => void;
  runParallelSimulation: (netlist: string) => Promise<void>;
}

export type SimulationSlice = SimulationState & SimulationActions;

export const createSimulationSlice: StateCreator<
  SimulationSlice & StoreWithTab,
  [],
  [],
  SimulationSlice
> = (set, get) => ({
  // Initial state
  netList: "",
  results: [],
  selectedSimType: "None",
  simulationConfig: undefined,
  allSimulationConfigs: [],
  bracketOperation: undefined,
  isParallelSimulationRunning: false,
  parallelSimulationProgress: {
    total: 0,
    completed: 0,
    successful: 0,
    failed: 0
  },
  parallelSimulationResults: undefined,

  // Netlist and simulation actions
  setNetList: (netList) => set({ netList }),
  setResults: (results) => set({ results }),

  // Simulation configuration actions
  setSelectedSimType: (type) => set({ selectedSimType: type }),
  setSimulationConfig: (config) => set({ simulationConfig: config }),
  setAllSimulationConfigs: (configs) => set({ allSimulationConfigs: configs }),

  addSimulationConfig: (config) =>
    set((state: SimulationSlice) => ({
      allSimulationConfigs: [...state.allSimulationConfigs, config],
    })),

  updateSimulationConfig: (index, config) =>
    set((state: SimulationSlice) => ({
      allSimulationConfigs: state.allSimulationConfigs.map((c, i) =>
        i === index ? config : c
      ),
    })),

  deleteSimulationConfig: (index) =>
    set((state: SimulationSlice) => ({
      allSimulationConfigs: state.allSimulationConfigs.filter(
        (_, i) => i !== index
      ),
    })),

  // Bracket operation actions
  setBracketOperation: (bracketOp) => set({ bracketOperation: bracketOp }),
  setParallelSimulationRunning: (running) => set({ isParallelSimulationRunning: running }),
  updateParallelSimulationProgress: (progress) => set({ parallelSimulationProgress: progress }),
  setParallelSimulationResults: (results) => set({ parallelSimulationResults: results }),
  resetParallelSimulation: () => set({
    bracketOperation: undefined,
    isParallelSimulationRunning: false,
    parallelSimulationProgress: { total: 0, completed: 0, successful: 0, failed: 0 },
    parallelSimulationResults: undefined
  }),

  // Combined actions for common operations
  exportNetlist: (netlist) => {
    const netListPreamble = `
* Netlist generated by EEcircuit
.include modelcard.CMOS90
`;
    const netlistWithPreamble = netListPreamble + netlist;

    set({
      netList: netlistWithPreamble,
      isSimulateTabEnabled: true,
      mainTabValue: "simulate",
    });
  },

  runParallelSimulation: async (netlist: string) => {
    const { findFirstBracketOperation } = await import("../utils/bracketParser");
    const { runParallelSimulation } = await import("../simulation/parallelSimulation");
    const { aggregateParallelResults } = await import("../simulation/resultAggregator");
    
    try {
      // Reset previous state
      const actions = get() as SimulationSlice & StoreWithTab;
      actions.resetParallelSimulation();
      
      // Find bracket operation
      const bracketOp = findFirstBracketOperation(netlist);
      if (!bracketOp) {
        throw new Error("No bracket operation found in netlist");
      }
      
      actions.setBracketOperation(bracketOp);
      actions.setParallelSimulationRunning(true);
      
      // Run parallel simulation
      const result = await runParallelSimulation(netlist, {
        maxWorkers: 4,
        onProgress: (completed, total, results) => {
          const successful = results.filter(r => r.success).length;
          const failed = results.length - successful;
          actions.updateParallelSimulationProgress({
            total,
            completed,
            successful,
            failed
          });
        },
        onResult: (result) => {
          // Handle individual result if needed
          console.log(`Individual result: ${result.parameterValue} - ${result.success ? 'success' : 'failed'}`);
        }
      });
      
      actions.setParallelSimulationResults(result);
      
      if (result.success && result.results.length > 0) {
        // Aggregate results for plotting
        const aggregated = aggregateParallelResults(result.results, bracketOp);
        if (aggregated) {
          // Update results and trigger plot tab using handleNewResults for bracket operation detection
          // Type assertion needed because AggregatedResult extends ResultType but with additional properties
          const appActions = get() as SimulationSlice & StoreWithTab & { handleNewResults: (results: any[]) => void };
          appActions.handleNewResults([aggregated as any]);
        }
      }
      
    } catch (error) {
      console.error("Parallel simulation failed:", error);
    } finally {
      const actions = get() as SimulationSlice & StoreWithTab;
      actions.setParallelSimulationRunning(false);
    }
  },
});
