import { Button, Flex, Menu } from "@chakra-ui/react";
import React, { Suspense, useEffect, useState } from "react";
import EditorCustom from "../editor/editorCustom";
import { useColorModeValue } from "../components/ui/color-mode";
import { Skeleton } from "@chakra-ui/react";
import { toaster } from "../components/ui/toaster";
import { X } from "lucide-react";
import { SimulationType, ToBePlotted } from "../types/commonTypes";
import {
  useSimulationState,
  usePlotSelectionState,
  useAppStore,
} from "../store/appStore";
import SimulationConfigPanel from "./SimulationConfigPanel";

type SimulationEditorProps = {
  netList: string;
  onSwitchToSchematic?: () => void;
};

const SimulationEditor: React.FC<SimulationEditorProps> = ({
  netList = "",
  onSwitchToSchematic,
}) => {
  // Get state and actions from Zustand store
  const { selectedSimType } = useSimulationState();

  const { toBePlotted, removeToBePlotted } = usePlotSelectionState();

  // Import handleNewResults from the main app store for handling simulation results
  const { handleNewResults } = useAppStore();

  // Local state for UI management
  const [netListToSim, setNetListToSim] = useState(netList);
  const [simCommandString, setSimCommandString] = useState("");

  const handleEditor = React.useCallback((value: string | undefined) => {
    if (value !== undefined) {
      setNetListToSim(value);
    }
  }, []);

  const saveCommandConfig = (toBePlotted: ToBePlotted[]) => {
    if (toBePlotted.length === 0) {
      return "";
    }

    const saveCommands = toBePlotted
      .map((item) => {
        if (item.type === "voltage") {
          return `v(${item.name})`;
        } else if (item.type === "current") {
          return `i(${item.name})`;
        }
        return "";
      })
      .filter((cmd) => cmd !== "");

    return `.save ${saveCommands.join(" ")}`;
  };

  // Update netlist when simulation type or configuration changes
  useEffect(() => {
    if (selectedSimType === "None") {
      setNetListToSim(netList);
      return;
    } else {
      const saveCommand = saveCommandConfig(toBePlotted);
      // Use the string command generated by config components
      const newNetList =
        netList +
        "\n\n" +
        simCommandString +
        "\n\n" +
        saveCommand +
        "\n\n" +
        ".end";
      setNetListToSim(newNetList);
    }
  }, [netList, simCommandString, selectedSimType, toBePlotted]);

  // Handler for string-based config changes from config components
  const handleStringConfigChange = React.useCallback((configString: string) => {
    // Store the generated SPICE command from config components
    setSimCommandString(configString);
  }, []);

  // Handler for receiving the full configuration object from config components
  const handleFullConfigChange = React.useCallback((config: SimulationType) => {
    // This function is called by the SimulationConfigPanel when configuration changes
    // The panel handles all the complex configuration management logic
    console.log("Configuration changed:", config);
  }, []);

  const handleSimRun = async () => {
    const { Simulation } = await import("eecircuit-engine");

    const sim = new Simulation();
    await sim.start();

    sim.setNetList(netListToSim);

    const result = await sim.runSim();

    if (result) {
      // Check if the result has valid data and variables
      const hasData = result.data && result.data.length > 0;
      const hasVariables =
        result.variableNames && result.variableNames.length > 0;

      // Additional check for actual data points in the result
      let hasDataPoints = false;
      if (hasData) {
        hasDataPoints = result.data.some(
          (dataSet) => dataSet.values && dataSet.values.length > 0
        );
      }

      if (!hasData || !hasVariables || !hasDataPoints) {
        // Show error toast for empty results
        toaster.create({
          title: "Simulation Error",
          description:
            "Simulation run but no results were generated. Check your netlist and simulation configuration.",
          type: "error",
          duration: 5000,
        });
        console.error("Simulation completed but returned empty results.");
        return; // Don't call handleNewResults, preventing tab switch
      }

      // Valid results, proceed normally
      handleNewResults([result]);
    } else {
      // Show error toast for failed simulation
      toaster.create({
        title: "Simulation Error",
        description: "Simulation failed to run. Check your netlist for errors.",
        type: "error",
        duration: 5000,
      });
      console.error("Simulation failed or returned no results.");
    }
  };

  return (
    <Flex
      width="100%"
      flexDirection={"row"}
      height="100%"
      overflow="hidden"
      position="relative"
      css={{
        "& *": {
          scrollbarWidth: "thin",
        },
        "&, & *": {
          overscrollBehavior: "contain",
        },
      }}
    >
      {/* Editor on the left */}
      <Flex flex="1" flexDirection="column" height="100%" overflow="hidden">
        <Flex
          padding="2"
          borderBottom="1px solid"
          borderColor={useColorModeValue("gray.200", "gray.600")}
          justifyContent="flex-start"
          alignItems="center"
          gap="2"
        >
          {/* "To Be Plotted" button with dropdown if items exist */}
          {toBePlotted.length > 0 ? (
            <Menu.Root>
              <Menu.Trigger asChild>
                <Button size="sm" variant="outline">
                  To Be Plotted ({toBePlotted.length})
                </Button>
              </Menu.Trigger>
              <Menu.Positioner>
                <Menu.Content>
                  {toBePlotted.map((item, index) => (
                    <Menu.Item key={index} value={`${item.type}-${item.name}`}>
                      <Flex
                        justifyContent="space-between"
                        alignItems="center"
                        width="100%"
                      >
                        <span>
                          {item.type === "voltage" ? "V" : "I"}({item.name})
                        </span>
                        <Button
                          size="xs"
                          variant="ghost"
                          onClick={(e: React.MouseEvent) => {
                            e.stopPropagation();
                            removeToBePlotted(item);
                          }}
                        >
                          <X size={12} />
                        </Button>
                      </Flex>
                    </Menu.Item>
                  ))}
                  <Menu.Separator />
                  <Menu.Item
                    value="add-more"
                    onClick={() => {
                      onSwitchToSchematic?.();
                    }}
                  >
                    Add More...
                  </Menu.Item>
                </Menu.Content>
              </Menu.Positioner>
            </Menu.Root>
          ) : (
            <Button
              size="sm"
              variant="outline"
              onClick={() => {
                onSwitchToSchematic?.();
              }}
            >
              To Be Plotted
            </Button>
          )}
        </Flex>

        <Suspense fallback={<Skeleton height="100%" width="100%" />}>
          <EditorCustom
            height="100%"
            width="100%"
            language="spice"
            value={netListToSim}
            valueChanged={handleEditor}
            theme={useColorModeValue("light", "dark")}
          />
        </Suspense>
      </Flex>

      {/* Simulation configuration panel on the right */}
      <SimulationConfigPanel
        onStringConfigChange={handleStringConfigChange}
        onFullConfigChange={handleFullConfigChange}
      />

      {/* Fixed simulation button at bottom right of config panel */}
      <Flex
        position="absolute"
        bottom="0"
        right="0"
        width="300px"
        maxWidth="400px"
        height="80px"
        padding="4"
        backgroundColor={useColorModeValue("white", "gray.800")}
        borderTop="1px solid"
        borderColor={useColorModeValue("gray.200", "gray.600")}
        alignItems="center"
      >
        <Button onClick={handleSimRun} width="100%">
          Run Simulation
        </Button>
      </Flex>
    </Flex>
  );
};

export default SimulationEditor;
