"use client";
import React from "react";

//const EditorCustom = React.lazy(() => import("./editor/editorCustom.tsx"));
//const PlotArray = React.lazy(() => import("./plotArray.tsx"));
//const DisplayBox = React.lazy(() => import("./displayBox.tsx"));

import { Box, Flex, Tabs, Text } from "@chakra-ui/react";

import { Toaster } from "./components/ui/toaster.tsx";

import Schematic from "./schematic/schematic.tsx";
import SimulationEditor from "./Simulate/simulate.tsx";
import { TabsValueChangeDetails } from "node_modules/@chakra-ui/react/dist/types/components/tabs/tabs";
import Logo from "./logo.tsx";
import Plot from "./plot/plot.tsx";
import { ResultType } from "eecircuit-engine";
import { sendCommand } from "eecircuit-schematic";
import { EEcircuitFile } from "./types/commonTypes.ts";

type TabsValue = "schematic" | "simulate" | "plot";

const EEcircuit: React.FC = () => {
  // Create the count state.

  const [netList, setNetList] = React.useState("");
  //const [displayData, setDisplayData] = React.useState<DisplayDataType[]>();
  const [tabValue, setTabValue] = React.useState<TabsValue>("schematic");
  const [shouldFitToScreen, setShouldFitToScreen] = React.useState(false);
  const [hasResizedSinceSchematicView, setHasResizedSinceSchematicView] =
    React.useState(false);
  const [hasViewedSchematic, setHasViewedSchematic] = React.useState(false);

  //const colorMode = useColorModeValue("light", "dark");

  const [results, setResults] = React.useState<ResultType[]>([]);

  // Tab enablement states
  const [isSimulateTabEnabled, setIsSimulateTabEnabled] = React.useState(false);
  const [isPlotTabEnabled, setIsPlotTabEnabled] = React.useState(false);

  const [dragBox, setDragBox] = React.useState(false);

  // Ref for the tabs container to handle drag and drop
  const tabsContainerRef = React.useRef<HTMLDivElement>(null);

  // Track window resize events
  React.useEffect(() => {
    const handleResize = () => {
      setHasResizedSinceSchematicView(true);
    };

    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  // Handle initial schematic view (when component mounts and schematic is the default tab)
  React.useEffect(() => {
    if (tabValue === "schematic" && !hasViewedSchematic) {
      // Delay the fit command to ensure canvas is ready
      const timer = setTimeout(() => {
        setShouldFitToScreen(true);
        setHasViewedSchematic(true);
      }, 200); // Longer delay for initial load
      return () => clearTimeout(timer);
    }
  }, [tabValue, hasViewedSchematic]);

  // Reset shouldFitToScreen flag after it's been processed
  React.useEffect(() => {
    if (shouldFitToScreen) {
      const timer = setTimeout(() => {
        setShouldFitToScreen(false);
      }, 100); // Small delay to ensure the command is processed
      return () => clearTimeout(timer);
    }
  }, [shouldFitToScreen]);

  // Callback when canvas is resized
  const handleCanvasResized = React.useCallback(() => {
    setHasResizedSinceSchematicView(false);
  }, []);

  const exportedNetlist = React.useCallback((netlist: string) => {
    const netListPreamble = `
* Netlist generated by EEcircuit
.include modelcard.CMOS90
`;

    const netlistWithPreamble = netListPreamble + netlist;
    setNetList(netlistWithPreamble);
    setIsSimulateTabEnabled(true); // Enable simulate tab when netlist is exported
    setTabValue("simulate");
  }, []);

  const handleTabValueChange = React.useCallback(
    (details: TabsValueChangeDetails) => {
      const newTabValue = details.value as TabsValue;

      // Prevent switching to disabled tabs
      if (newTabValue === "simulate" && !isSimulateTabEnabled) {
        return;
      }
      if (newTabValue === "plot" && !isPlotTabEnabled) {
        return;
      }

      setTabValue(newTabValue);

      // Handle schematic tab activation
      if (newTabValue === "schematic") {
        // Fit to screen if this is the first time viewing or if window was resized
        if (!hasViewedSchematic || hasResizedSinceSchematicView) {
          // Small delay to ensure tab content is visible and canvas is ready
          setTimeout(() => {
            setShouldFitToScreen(true);
            setHasViewedSchematic(true);
            // Note: hasResizedSinceSchematicView will be reset by the onCanvasResized callback
            // when the canvas is actually resized, not immediately here
          }, 100);
        }
      } else {
        // Reset fit to screen flag when leaving schematic tab
        setShouldFitToScreen(false);
      }
    },
    [
      hasViewedSchematic,
      hasResizedSinceSchematicView,
      isSimulateTabEnabled,
      isPlotTabEnabled,
    ]
  );

  // Add drag and drop support for schematic files
  React.useEffect(() => {
    const container = tabsContainerRef.current;
    if (!container) return;

    const preventDefault = (e: DragEvent) => {
      e.preventDefault();
      e.stopPropagation();
    };

    // Validate file type - accept common schematic file extensions
    const isValidSchematicFile = (file: File): boolean => {
      return (
        file.type === "application/json" ||
        file.type === "text/plain" ||
        file.type === "application/xml"
      );
    };

    const handleDragOver = (e: DragEvent) => {
      preventDefault(e);
      // Only show visual feedback if we have files
      if (e.dataTransfer?.items && e.dataTransfer.items.length > 0) {
        setDragBox(true);
      }
    };

    const handleDragLeave = (e: DragEvent) => {
      preventDefault(e);
      // Only hide dragBox if we're actually leaving the container
      // Check if the related target is still within our container
      const relatedTarget = e.relatedTarget as Node;
      if (!relatedTarget || !container.contains(relatedTarget)) {
        setDragBox(false);
      }
    };

    const handleDrop = async (e: DragEvent) => {
      preventDefault(e);
      setDragBox(false);

      const files = e.dataTransfer?.files;
      if (!files?.length) return;

      const file = files[0];

      // Validate file type
      if (!isValidSchematicFile(file)) {
        console.warn(
          "Invalid file type dropped. Please drop a valid schematic file."
        );
        return;
      }

      try {
        const content = await file.text();
        const parsedContent: EEcircuitFile = JSON.parse(content);
        // check the schema version is correct
        if (parsedContent.schema !== "EEcircuitV1") {
          console.error(
            "Invalid schema version. Please drop a valid EEcircuit file."
          );
          return;
        }
        if (parsedContent.schematic) {
          // Use the imported sendCommand from eecircuit-schematic
          await sendCommand({
            command: "loadSchematic",
            schematic: parsedContent.schematic,
          });
          console.log(
            "Schematic loaded successfully from dropped file:",
            file.name
          );
        }
      } catch (error) {
        console.error("Failed to load schematic from dropped file:", error);
        alert(
          "Failed to load schematic from dropped file. Please ensure the file is valid."
        );
      }
    };

    // Add event listeners
    container.addEventListener("dragover", handleDragOver);
    container.addEventListener("dragenter", preventDefault);
    container.addEventListener("dragleave", handleDragLeave);
    container.addEventListener("drop", handleDrop);

    // Clean up
    return () => {
      container.removeEventListener("dragover", handleDragOver);
      container.removeEventListener("dragenter", preventDefault);
      container.removeEventListener("dragleave", handleDragLeave);
      container.removeEventListener("drop", handleDrop);
    };
  }, []); // Remove dragBox dependency to prevent unnecessary re-registrations

  const handleNewResults = React.useCallback((newResults: ResultType[]) => {
    // Double-check that we have valid results before enabling plot tab
    const hasValidResults =
      newResults &&
      newResults.length > 0 &&
      newResults[0].data &&
      newResults[0].data.length > 0 &&
      newResults[0].variableNames &&
      newResults[0].variableNames.length > 0;

    // Additional check for actual data points
    let hasDataPoints = false;
    if (hasValidResults) {
      hasDataPoints = newResults[0].data.some(
        (dataSet) => dataSet.values && dataSet.values.length > 0
      );
    }

    if (hasValidResults && hasDataPoints) {
      setResults(newResults);
      setIsPlotTabEnabled(true); // Enable plot tab when valid results are obtained
      setTabValue("plot");
    } else {
      // This should not happen if simulate.tsx is working correctly, but just in case
      console.warn(
        "handleNewResults called with invalid results, not enabling plot tab"
      );
    }
  }, []);

  return (
    <Box
      border="solid 0px"
      p={2}
      height={"100vh"}
      display={"flex"}
      flexDirection={"column"}
      overflow="hidden"
    >
      <Flex direction="row" alignItems={"self-end"} gapX={2} flexShrink={0}>
        <Logo />
        <Text>a SPICE based circuit simulator</Text>
      </Flex>

      <Tabs.Root
        ref={tabsContainerRef}
        defaultValue="schematic"
        value={tabValue}
        onValueChange={handleTabValueChange}
        variant="subtle"
        display={"flex"}
        flexDirection="column"
        flex={1}
        minHeight={0}
        position="relative"
      >
        {dragBox ? (
          <Box
            bg="blue.400/80"
            width="100%"
            height="100%"
            position="absolute"
            top={0}
            left={0}
            zIndex={1000}
          >
            <Flex
              direction="column"
              alignItems="center"
              justifyContent="center"
              width="100%"
              height="100%"
            >
              <Box
                p={4}
                color="gray.100"
                fontSize="5xl"
                width="50%"
                textAlign="center"
              >
                Drop schematic file here!
              </Box>
            </Flex>
          </Box>
        ) : null}
        <Tabs.List flexShrink={0}>
          <Tabs.Trigger value="schematic" marginRight="0.5em">
            Schematic
          </Tabs.Trigger>
          <Tabs.Trigger
            value="simulate"
            marginRight="0.5em"
            disabled={!isSimulateTabEnabled}
            style={{
              opacity: isSimulateTabEnabled ? 1 : 0.5,
              cursor: isSimulateTabEnabled ? "pointer" : "not-allowed",
            }}
          >
            Simulate
          </Tabs.Trigger>
          <Tabs.Trigger
            value="plot"
            marginRight="0.5em"
            disabled={!isPlotTabEnabled}
            style={{
              opacity: isPlotTabEnabled ? 1 : 0.5,
              cursor: isPlotTabEnabled ? "pointer" : "not-allowed",
            }}
          >
            Plot
          </Tabs.Trigger>
        </Tabs.List>

        <Tabs.Content value="schematic" flex={1} minHeight={0}>
          <Schematic
            onNetlistExported={exportedNetlist}
            shouldFitToScreen={shouldFitToScreen}
            onCanvasResized={handleCanvasResized}
          />
        </Tabs.Content>

        <Tabs.Content value="simulate" flex={1} minHeight={0}>
          <SimulationEditor
            netList={netList}
            onResultsObtained={handleNewResults}
          />
        </Tabs.Content>

        <Tabs.Content value="plot" flex={1} minHeight={0}>
          <Plot results={results} />
          {/* <PlotArray
              resultArray={resultArray}
              displayData={displayData}
              colorMode={colorMode}
              sweep={sweep}
              info={info}
              progress={progress}
              threadCount={threadCount}
              setThreadCount={setThreadCountNew}
            /> */}
        </Tabs.Content>
      </Tabs.Root>
      <Toaster />
    </Box>
  );
};

export default EEcircuit;
