"use client";
import React from "react";

//const EditorCustom = React.lazy(() => import("./editor/editorCustom.tsx"));
//const PlotArray = React.lazy(() => import("./plotArray.tsx"));
//const DisplayBox = React.lazy(() => import("./displayBox.tsx"));

import { Box, Flex, Tabs, Text } from "@chakra-ui/react";

import { Toaster } from "./components/ui/toaster.tsx";

import Schematic from "./schematic/schematic.tsx";
import SimulationEditor from "./Simulate/simulate.tsx";
import { TabsValueChangeDetails } from "node_modules/@chakra-ui/react/dist/types/components/tabs/tabs";
import Logo from "./logo.tsx";
import Plot from "./plot/plot.tsx";
import * as eeSch from "eecircuit-engine";

type TabsValue = "schematic" | "simulate" | "plot";

const EEcircuit: React.FC = () => {
  // Create the count state.

  const [netList, setNetList] = React.useState("");
  //const [displayData, setDisplayData] = React.useState<DisplayDataType[]>();
  const [tabValue, setTabValue] = React.useState<TabsValue>("schematic");
  const [shouldFitToScreen, setShouldFitToScreen] = React.useState(false);
  const [hasResizedSinceSchematicView, setHasResizedSinceSchematicView] =
    React.useState(false);
  const [hasViewedSchematic, setHasViewedSchematic] = React.useState(false);

  //const colorMode = useColorModeValue("light", "dark");

  const [results, setResults] = React.useState<eeSch.ResultType[]>([]);

  // Tab enablement states
  const [isSimulateTabEnabled, setIsSimulateTabEnabled] = React.useState(false);
  const [isPlotTabEnabled, setIsPlotTabEnabled] = React.useState(false);

  // Track window resize events
  React.useEffect(() => {
    const handleResize = () => {
      setHasResizedSinceSchematicView(true);
    };

    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  // Handle initial schematic view (when component mounts and schematic is the default tab)
  React.useEffect(() => {
    if (tabValue === "schematic" && !hasViewedSchematic) {
      // Delay the fit command to ensure canvas is ready
      const timer = setTimeout(() => {
        setShouldFitToScreen(true);
        setHasViewedSchematic(true);
      }, 200); // Longer delay for initial load
      return () => clearTimeout(timer);
    }
  }, [tabValue, hasViewedSchematic]);

  // Reset shouldFitToScreen flag after it's been processed
  React.useEffect(() => {
    if (shouldFitToScreen) {
      const timer = setTimeout(() => {
        setShouldFitToScreen(false);
      }, 100); // Small delay to ensure the command is processed
      return () => clearTimeout(timer);
    }
  }, [shouldFitToScreen]);

  // Callback when canvas is resized
  const handleCanvasResized = React.useCallback(() => {
    setHasResizedSinceSchematicView(false);
  }, []);

  const exportedNetlist = React.useCallback((netlist: string) => {
    const netListPreamble = `
* Netlist generated by EEcircuit
.include modelcard.CMOS90
`;

    const netlistWithPreamble = netListPreamble + netlist;
    setNetList(netlistWithPreamble);
    setIsSimulateTabEnabled(true); // Enable simulate tab when netlist is exported
    setTabValue("simulate");
  }, []);

  const handleTabValueChange = React.useCallback(
    (details: TabsValueChangeDetails) => {
      const newTabValue = details.value as TabsValue;

      // Prevent switching to disabled tabs
      if (newTabValue === "simulate" && !isSimulateTabEnabled) {
        return;
      }
      if (newTabValue === "plot" && !isPlotTabEnabled) {
        return;
      }

      setTabValue(newTabValue);

      // Handle schematic tab activation
      if (newTabValue === "schematic") {
        // Fit to screen if this is the first time viewing or if window was resized
        if (!hasViewedSchematic || hasResizedSinceSchematicView) {
          // Small delay to ensure tab content is visible and canvas is ready
          setTimeout(() => {
            setShouldFitToScreen(true);
            setHasViewedSchematic(true);
            // Note: hasResizedSinceSchematicView will be reset by the onCanvasResized callback
            // when the canvas is actually resized, not immediately here
          }, 100);
        }
      } else {
        // Reset fit to screen flag when leaving schematic tab
        setShouldFitToScreen(false);
      }
    },
    [
      hasViewedSchematic,
      hasResizedSinceSchematicView,
      isSimulateTabEnabled,
      isPlotTabEnabled,
    ]
  );

  const handleNewResults = React.useCallback(
    (newResults: eeSch.ResultType[]) => {
      // Double-check that we have valid results before enabling plot tab
      const hasValidResults =
        newResults &&
        newResults.length > 0 &&
        newResults[0].data &&
        newResults[0].data.length > 0 &&
        newResults[0].variableNames &&
        newResults[0].variableNames.length > 0;

      // Additional check for actual data points
      let hasDataPoints = false;
      if (hasValidResults) {
        hasDataPoints = newResults[0].data.some(
          (dataSet) => dataSet.values && dataSet.values.length > 0
        );
      }

      if (hasValidResults && hasDataPoints) {
        setResults(newResults);
        setIsPlotTabEnabled(true); // Enable plot tab when valid results are obtained
        setTabValue("plot");
      } else {
        // This should not happen if simulate.tsx is working correctly, but just in case
        console.warn(
          "handleNewResults called with invalid results, not enabling plot tab"
        );
      }
    },
    []
  );

  return (
    <Box
      border="solid 0px"
      p={2}
      height={"100vh"}
      display={"flex"}
      flexDirection={"column"}
      overflow="hidden"
    >
      <Flex direction="row" alignItems={"self-end"} gapX={2} flexShrink={0}>
        <Logo />
        <Text>a SPICE based circuit simulator</Text>
      </Flex>
      <Tabs.Root
        defaultValue="schematic"
        value={tabValue}
        onValueChange={handleTabValueChange}
        variant="subtle"
        display={"flex"}
        flexDirection="column"
        flex={1}
        minHeight={0}
      >
        <Tabs.List flexShrink={0}>
          <Tabs.Trigger value="schematic" marginRight="0.5em">
            Schematic
          </Tabs.Trigger>
          <Tabs.Trigger
            value="simulate"
            marginRight="0.5em"
            disabled={!isSimulateTabEnabled}
            style={{
              opacity: isSimulateTabEnabled ? 1 : 0.5,
              cursor: isSimulateTabEnabled ? "pointer" : "not-allowed",
            }}
          >
            Simulate
          </Tabs.Trigger>
          <Tabs.Trigger
            value="plot"
            marginRight="0.5em"
            disabled={!isPlotTabEnabled}
            style={{
              opacity: isPlotTabEnabled ? 1 : 0.5,
              cursor: isPlotTabEnabled ? "pointer" : "not-allowed",
            }}
          >
            Plot
          </Tabs.Trigger>
        </Tabs.List>

        <Tabs.Content value="schematic" flex={1} minHeight={0}>
          <Schematic
            onNetlistExported={exportedNetlist}
            shouldFitToScreen={shouldFitToScreen}
            onCanvasResized={handleCanvasResized}
          />
        </Tabs.Content>

        <Tabs.Content value="simulate" flex={1} minHeight={0}>
          <SimulationEditor
            netList={netList}
            onResultsObtained={handleNewResults}
          />
        </Tabs.Content>

        <Tabs.Content value="plot" flex={1} minHeight={0}>
          <Plot results={results} />
          {/* <PlotArray
              resultArray={resultArray}
              displayData={displayData}
              colorMode={colorMode}
              sweep={sweep}
              info={info}
              progress={progress}
              threadCount={threadCount}
              setThreadCount={setThreadCountNew}
            /> */}
        </Tabs.Content>
      </Tabs.Root>
      <Toaster />
    </Box>
  );
};

export default EEcircuit;
