"use client";
import React from "react";

//const EditorCustom = React.lazy(() => import("./editor/editorCustom.tsx"));
//const PlotArray = React.lazy(() => import("./plotArray.tsx"));
//const DisplayBox = React.lazy(() => import("./displayBox.tsx"));

import { Box, Flex, Tabs, Text, IconButton } from "@chakra-ui/react";

import { Toaster } from "./components/ui/toaster.tsx";
import { Tooltip } from "./components/ui/tooltip.tsx";

import Schematic from "./schematic/schematic.tsx";
import SimulationEditor from "./Simulate/simulate.tsx";
import { TabsValueChangeDetails } from "node_modules/@chakra-ui/react/dist/types/components/tabs/tabs";
import Logo from "./logo.tsx";
import Plot from "./plot/plot.tsx";
import { ResultType } from "eecircuit-engine";
import { sendCommand } from "eecircuit-schematic";
import {
  EEcircuitFile,
  SimulationType,
  ToBePlotted,
} from "./types/commonTypes.ts";
import { Mouse, Touchpad } from "lucide-react";

type TabsValue = "schematic" | "simulate" | "plot";

const EEcircuit: React.FC = () => {
  // Create the count state.

  const [netList, setNetList] = React.useState("");
  //const [displayData, setDisplayData] = React.useState<DisplayDataType[]>();
  const [tabValue, setTabValue] = React.useState<TabsValue>("schematic");
  const [shouldFitToScreen, setShouldFitToScreen] = React.useState(false);
  const [hasResizedSinceSchematicView, setHasResizedSinceSchematicView] =
    React.useState(false);
  const [hasViewedSchematic, setHasViewedSchematic] = React.useState(false);

  //const colorMode = useColorModeValue("light", "dark");

  const [results, setResults] = React.useState<ResultType[]>([]);

  // Simulation configuration state - uplifted from SimulationEditor
  const [selectedSimType, setSelectedSimType] = React.useState("None");
  const [simulationConfig, setSimulationConfig] = React.useState<
    SimulationType | undefined
  >(undefined);

  // Handler for simulation configuration changes
  const handleSimulationConfigChange = React.useCallback(
    (simType: string, config?: SimulationType) => {
      console.log("Simulation config change:", { simType, config });
      setSelectedSimType(simType);
      setSimulationConfig(config);
    },
    []
  );

  // Callback to get current simulation config for saving
  const getCurrentSimulationConfig = React.useCallback(() => {
    console.log(
      "Getting current simulation config for saving:",
      simulationConfig
    );
    return simulationConfig;
  }, [simulationConfig]);

  // Tab enablement states
  const [isSimulateTabEnabled, setIsSimulateTabEnabled] = React.useState(false);
  const [isPlotTabEnabled, setIsPlotTabEnabled] = React.useState(false);

  // Input profile state - defaults to trackpad
  const [inputProfile, setInputProfile] = React.useState<"mouse" | "trackpad">(
    "trackpad"
  );

  // Plot selection mode state
  const [isPlotSelectionMode, setIsPlotSelectionMode] = React.useState(false);
  const [toBePlotted, setToBePlotted] = React.useState<ToBePlotted[]>([]);

  const [dragBox, setDragBox] = React.useState(false);

  // Ref for the tabs container to handle drag and drop
  const tabsContainerRef = React.useRef<HTMLDivElement>(null);

  // Track window resize events
  React.useEffect(() => {
    const handleResize = () => {
      setHasResizedSinceSchematicView(true);
    };

    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  // Handle initial schematic view (when component mounts and schematic is the default tab)
  React.useEffect(() => {
    if (tabValue === "schematic" && !hasViewedSchematic) {
      // Delay the fit command to ensure canvas is ready
      const timer = setTimeout(() => {
        setShouldFitToScreen(true);
        setHasViewedSchematic(true);
      }, 200); // Longer delay for initial load
      return () => clearTimeout(timer);
    }
  }, [tabValue, hasViewedSchematic]);

  // Reset shouldFitToScreen flag after it's been processed
  React.useEffect(() => {
    if (shouldFitToScreen) {
      const timer = setTimeout(() => {
        setShouldFitToScreen(false);
      }, 100); // Small delay to ensure the command is processed
      return () => clearTimeout(timer);
    }
  }, [shouldFitToScreen]);

  // Callback when canvas is resized
  const handleCanvasResized = React.useCallback(() => {
    setHasResizedSinceSchematicView(false);
  }, []);

  const exportedNetlist = React.useCallback((netlist: string) => {
    const netListPreamble = `
* Netlist generated by EEcircuit
.include modelcard.CMOS90
`;

    const netlistWithPreamble = netListPreamble + netlist;
    setNetList(netlistWithPreamble);
    setIsSimulateTabEnabled(true); // Enable simulate tab when netlist is exported
    setTabValue("simulate");
  }, []);

  const handleTabValueChange = React.useCallback(
    (details: TabsValueChangeDetails) => {
      const newTabValue = details.value as TabsValue;

      // Prevent switching to disabled tabs
      if (newTabValue === "simulate" && !isSimulateTabEnabled) {
        return;
      }
      if (newTabValue === "plot" && !isPlotTabEnabled) {
        return;
      }

      setTabValue(newTabValue);

      // Handle schematic tab activation
      if (newTabValue === "schematic") {
        // IMPORTANT: Only use fit-to-screen for initial app initialization or window resize
        // NEVER use fit-to-screen for regular tab switches - view restoration handles that
        if (!hasViewedSchematic || hasResizedSinceSchematicView) {
          // Small delay to ensure tab content is visible and canvas is ready
          setTimeout(() => {
            console.log(
              "Setting fit-to-screen for initial app initialization or window resize"
            );
            setShouldFitToScreen(true);
            setHasViewedSchematic(true);
            // Note: hasResizedSinceSchematicView will be reset by the onCanvasResized callback
            // when the canvas is actually resized, not immediately here
          }, 100);
        } else {
          // For regular tab switches, do NOT use fit-to-screen
          // The schematic component has its own view restoration logic that preserves user's zoom/pan
          console.log(
            "Regular tab switch to schematic - relying on schematic component's view restoration"
          );
        }
      } else {
        // Reset fit to screen flag when leaving schematic tab
        setShouldFitToScreen(false);
      }
    },
    [
      hasViewedSchematic,
      hasResizedSinceSchematicView,
      isSimulateTabEnabled,
      isPlotTabEnabled,
    ]
  );

  // Add drag and drop support for schematic files
  React.useEffect(() => {
    const container = tabsContainerRef.current;
    if (!container) return;

    const preventDefault = (e: DragEvent) => {
      e.preventDefault();
      e.stopPropagation();
    };

    // Validate file type - accept common schematic file extensions
    const isValidSchematicFile = (file: File): boolean => {
      return (
        file.type === "application/json" ||
        file.type === "text/plain" ||
        file.type === "application/xml"
      );
    };

    const handleDragOver = (e: DragEvent) => {
      preventDefault(e);
      // Only show visual feedback if we have files
      if (e.dataTransfer?.items && e.dataTransfer.items.length > 0) {
        setDragBox(true);
      }
    };

    const handleDragLeave = (e: DragEvent) => {
      preventDefault(e);
      // Only hide dragBox if we're actually leaving the container
      // Check if the related target is still within our container
      const relatedTarget = e.relatedTarget as Node;
      if (!relatedTarget || !container.contains(relatedTarget)) {
        setDragBox(false);
      }
    };

    const handleDrop = async (e: DragEvent) => {
      preventDefault(e);
      setDragBox(false);

      const files = e.dataTransfer?.files;
      if (!files?.length) return;

      const file = files[0];

      // Validate file type
      if (!isValidSchematicFile(file)) {
        console.warn(
          "Invalid file type dropped. Please drop a valid schematic file."
        );
        return;
      }

      try {
        const content = await file.text();
        const parsedContent: EEcircuitFile = JSON.parse(content);
        // check the schema version is correct
        if (parsedContent.schema !== "EEcircuitV1") {
          console.error(
            "Invalid schema version. Please drop a valid EEcircuit file."
          );
          return;
        }
        if (parsedContent.schematic) {
          // Use the imported sendCommand from eecircuit-schematic
          await sendCommand({
            command: "loadSchematic",
            schematic: parsedContent.schematic,
          });
          console.log(
            "Schematic loaded successfully from dropped file:",
            file.name
          );
        }

        // Restore simulation configuration if it exists
        if (parsedContent.simulation) {
          const simConfig = parsedContent.simulation;
          // Set the simulation type and configuration based on loaded data
          setSelectedSimType(
            simConfig.type === "Transient" ? "Trans" : simConfig.type
          );
          setSimulationConfig(simConfig);
          console.log("Simulation configuration restored:", simConfig);
        } else {
          // Reset simulation config if no simulation data in file
          setSimulationConfig(undefined);
          setSelectedSimType("None");
        }
      } catch (error) {
        console.error("Failed to load schematic from dropped file:", error);
        alert(
          "Failed to load schematic from dropped file. Please ensure the file is valid."
        );
      }
    };

    // Add event listeners
    container.addEventListener("dragover", handleDragOver);
    container.addEventListener("dragenter", preventDefault);
    container.addEventListener("dragleave", handleDragLeave);
    container.addEventListener("drop", handleDrop);

    // Clean up
    return () => {
      container.removeEventListener("dragover", handleDragOver);
      container.removeEventListener("dragenter", preventDefault);
      container.removeEventListener("dragleave", handleDragLeave);
      container.removeEventListener("drop", handleDrop);
    };
  }, []); // Remove dragBox dependency to prevent unnecessary re-registrations

  const handleNewResults = React.useCallback((newResults: ResultType[]) => {
    // Double-check that we have valid results before enabling plot tab
    const hasValidResults =
      newResults &&
      newResults.length > 0 &&
      newResults[0].data &&
      newResults[0].data.length > 0 &&
      newResults[0].variableNames &&
      newResults[0].variableNames.length > 0;

    // Additional check for actual data points
    let hasDataPoints = false;
    if (hasValidResults) {
      hasDataPoints = newResults[0].data.some(
        (dataSet) => dataSet.values && dataSet.values.length > 0
      );
    }

    if (hasValidResults && hasDataPoints) {
      setResults(newResults);
      setIsPlotTabEnabled(true); // Enable plot tab when valid results are obtained
      setTabValue("plot");
    } else {
      // This should not happen if simulate.tsx is working correctly, but just in case
      console.warn(
        "handleNewResults called with invalid results, not enabling plot tab"
      );
    }
  }, []);

  // Handler for input profile toggle
  const handleInputProfileToggle = React.useCallback(() => {
    const newProfile = inputProfile === "mouse" ? "trackpad" : "mouse";
    setInputProfile(newProfile);

    // Send command to update input profile in schematic canvas
    sendCommand({
      command: "setInputProfile",
      profile: newProfile,
    });

    console.log("Input profile changed to:", newProfile);
  }, [inputProfile]);

  // Handler for switching to schematic for plot selection
  const handleSwitchToSchematicForPlotSelection = React.useCallback(() => {
    setIsPlotSelectionMode(true);
    setTabValue("schematic");
  }, []);

  // Handler for when a plot item is selected in schematic
  const handlePlotItemSelected = React.useCallback((item: ToBePlotted) => {
    setToBePlotted((prev) => {
      // Check if item already exists
      const exists = prev.some(
        (existing) => existing.type === item.type && existing.name === item.name
      );

      if (!exists) {
        return [...prev, item];
      }

      return prev;
    });
  }, []);

  // Handler for exiting plot selection mode
  const handleExitPlotSelectionMode = React.useCallback(() => {
    setIsPlotSelectionMode(false);
    setTabValue("simulate");
  }, []);

  return (
    <Box
      border="solid 0px"
      p={2}
      height={"100vh"}
      display={"flex"}
      flexDirection={"column"}
      overflow="hidden"
    >
      <Flex direction="row" alignItems={"self-end"} gapX={2} flexShrink={0}>
        <Logo />
        <Text>a SPICE based circuit simulator</Text>
      </Flex>

      <Tabs.Root
        ref={tabsContainerRef}
        defaultValue="schematic"
        value={tabValue}
        onValueChange={handleTabValueChange}
        variant="subtle"
        display={"flex"}
        flexDirection="column"
        flex={1}
        minHeight={0}
        position="relative"
      >
        {dragBox ? (
          <Box
            bg="blue.400/80"
            width="100%"
            height="100%"
            position="absolute"
            top={0}
            left={0}
            zIndex={1000}
          >
            <Flex
              direction="column"
              alignItems="center"
              justifyContent="center"
              width="100%"
              height="100%"
            >
              <Box
                p={4}
                color="gray.100"
                fontSize="5xl"
                width="50%"
                textAlign="center"
              >
                Drop schematic file here!
              </Box>
            </Flex>
          </Box>
        ) : null}
        <Tabs.List flexShrink={0}>
          <Flex width="100%" alignItems="center" justifyContent="space-between">
            <Flex alignItems="center">
              <Tabs.Trigger value="schematic" marginRight="0.5em">
                Schematic
              </Tabs.Trigger>
              <Tabs.Trigger
                value="simulate"
                marginRight="0.5em"
                disabled={!isSimulateTabEnabled}
                style={{
                  opacity: isSimulateTabEnabled ? 1 : 0.5,
                  cursor: isSimulateTabEnabled ? "pointer" : "not-allowed",
                }}
              >
                Simulate
              </Tabs.Trigger>
              <Tabs.Trigger
                value="plot"
                marginRight="0.5em"
                disabled={!isPlotTabEnabled}
                style={{
                  opacity: isPlotTabEnabled ? 1 : 0.5,
                  cursor: isPlotTabEnabled ? "pointer" : "not-allowed",
                }}
              >
                Plot
              </Tabs.Trigger>
            </Flex>

            {/* Input Profile Toggle Button */}
            <Tooltip
              showArrow
              content={`Switch to ${inputProfile === "mouse" ? "trackpad" : "mouse"} input profile`}
              positioning={{ placement: "bottom" }}
            >
              <IconButton
                aria-label={`Switch to ${inputProfile === "mouse" ? "trackpad" : "mouse"} input profile`}
                size="sm"
                variant="ghost"
                onClick={handleInputProfileToggle}
              >
                {inputProfile === "mouse" ? (
                  <Mouse size={16} />
                ) : (
                  <Touchpad size={16} />
                )}
              </IconButton>
            </Tooltip>
          </Flex>
        </Tabs.List>

        <Tabs.Content value="schematic" flex={1} minHeight={0}>
          <Schematic
            onNetlistExported={exportedNetlist}
            shouldFitToScreen={shouldFitToScreen}
            onCanvasResized={handleCanvasResized}
            getSimulationConfig={getCurrentSimulationConfig}
            isPlotSelectionMode={isPlotSelectionMode}
            onPlotItemSelected={handlePlotItemSelected}
            onExitPlotSelectionMode={handleExitPlotSelectionMode}
          />
        </Tabs.Content>

        <Tabs.Content value="simulate" flex={1} minHeight={0}>
          <SimulationEditor
            netList={netList}
            onResultsObtained={handleNewResults}
            selectedSimType={selectedSimType}
            simulationConfig={simulationConfig}
            onSimulationConfigChange={handleSimulationConfigChange}
            onSwitchToSchematic={handleSwitchToSchematicForPlotSelection}
            toBePlotted={toBePlotted}
          />
        </Tabs.Content>

        <Tabs.Content value="plot" flex={1} minHeight={0}>
          <Plot results={results} />
          {/* <PlotArray
              resultArray={resultArray}
              displayData={displayData}
              colorMode={colorMode}
              sweep={sweep}
              info={info}
              progress={progress}
              threadCount={threadCount}
              setThreadCount={setThreadCountNew}
            /> */}
        </Tabs.Content>
      </Tabs.Root>
      <Toaster />
    </Box>
  );
};

export default EEcircuit;
