name: Main Build Test

on:
  schedule:
    - cron: "30 3 * * 0" # Runs every Sunday at 03:30 UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: eelab-dev/EEcircuit

      - name: Update Dependencies
        run: npx --yes npm-check-updates -u

      - name: Install Dependencies
        run: npm install

      - name: Build locally
        run: npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test -g "EEcircuit Prod"

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
